services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: screen_match
    volumes:
      - polls_pg_data:/var/lib/postgresql/data

volumes:
  polls_pg_data:
